Rename ukrainian cities to proper spelling
tkuchiki/go-timezone pull request #29
Opened 2024-03-28 20:35 UTC by bgr11n

Please, rename ukrainian cities to use up-to-date spelling, examples from wiki:
- [Kyiv](https://en.wikipedia.org/wiki/Kyiv)
- [Zaporizhzhia](https://en.wikipedia.org/wiki/Zaporizhzhia)
- [Uzhhorod](https://en.wikipedia.org/wiki/Uzhhorod)

Also maybe it make sense to have separately some id or slug field that should be persistent and name that may change?

2024-04-09 01:55 UTC, tkuchiki commented
@bgr11n Thank you for creating a PR, and I'm sorry for the late response.
I will check it later.

> Also maybe it make sense to have separately some id or slug field that should be persistent and name that may change?

You're right, so I will improve it later, thank you!

2024-04-09 02:57 UTC, tkuchiki requested changes
Could you please add it rather than rename it for backward compatibility?

2024-04-09 02:57 UTC, tkuchiki commented on timezones.go
> +		"Europe/Kyiv",
```suggestion
		"Europe/Kiev",
		"Europe/Kyiv",
```

2024-04-09 02:57 UTC, tkuchiki commented on timezones.go
> +		"Europe/Uzhhorod",
```suggestion
		"Europe/Uzhgorod",
		"Europe/Uzhhorod",
```

2024-04-09 02:57 UTC, tkuchiki commented on timezones.go
> +		"Europe/Zaporizhzhia",
```suggestion
		"Europe/Zaporozhye",
		"Europe/Zaporizhzhia",
```

2024-04-09 02:57 UTC, tkuchiki commented on timezones.go
> +		"Europe/Kyiv",
```suggestion
		"Europe/Kiev",
		"Europe/Kyiv",
```

2024-04-09 02:57 UTC, tkuchiki commented on timezones.go
> +		"Europe/Uzhhorod",
```suggestion
		"Europe/Uzhgorod",
		"Europe/Uzhhorod",
```

2024-04-09 02:57 UTC, tkuchiki commented on timezones.go
> +		"Europe/Zaporizhzhia",
```suggestion
		"Europe/Zaporozhye",
		"Europe/Zaporizhzhia",
```

2024-04-09 02:57 UTC, tkuchiki commented on tz_infos.go
> -	"Europe/Kiev": &TzInfo{
```go
	"Europe/Kiev": &TzInfo{
		longGeneric:        "Eastern European Time",
		longStandard:       "Eastern European Standard Time",
		longDaylight:       "Eastern European Summer Time",
		shortGeneric:       "EET",
		shortStandard:      "EET",
		shortDaylight:      "EEST",
		standardOffset:     7200,
		daylightOffset:     10800,
		standardOffsetHHMM: "+02:00",
		daylightOffsetHHMM: "+03:00",
		countryCode:        "UA",
		isDeprecated:       false,
		linkTo:             "",
		lastDST:            2037,
	},
```

2024-04-09 02:57 UTC, tkuchiki commented on tz_infos.go
> -	"Europe/Uzhgorod": &TzInfo{
```go
	"Europe/Uzhgorod": &TzInfo{
		longGeneric:        "Eastern European Time",
		longStandard:       "Eastern European Standard Time",
		longDaylight:       "Eastern European Summer Time",
		shortGeneric:       "EET",
		shortStandard:      "EET",
		shortDaylight:      "EEST",
		standardOffset:     7200,
		daylightOffset:     10800,
		standardOffsetHHMM: "+02:00",
		daylightOffsetHHMM: "+03:00",
		countryCode:        "UA",
		isDeprecated:       false,
		linkTo:             "",
		lastDST:            2037,
	},
```

2024-04-09 02:57 UTC, tkuchiki commented on tz_infos.go
> -	"Europe/Zaporozhye": &TzInfo{
```go
	"Europe/Zaporozhye": &TzInfo{
		longGeneric:        "Eastern European Time",
		longStandard:       "Eastern European Standard Time",
		longDaylight:       "Eastern European Summer Time",
		shortGeneric:       "EET",
		shortStandard:      "EET",
		shortDaylight:      "EEST",
		standardOffset:     7200,
		daylightOffset:     10800,
		standardOffsetHHMM: "+02:00",
		daylightOffsetHHMM: "+03:00",
		countryCode:        "UA",
		isDeprecated:       false,
		linkTo:             "",
		lastDST:            2037,
	},
```

2024-04-09 06:25 UTC, bgr11n commented
@tkuchiki But in that case there will be duplicates?

2024-04-10 14:49 UTC, tkuchiki commented
Yes. In that case, do you have any concerns?

2024-04-10 15:55 UTC, bgr11n commented
@tkuchiki No, just wanted to clarify that it is expected.

2024-04-12 13:49 UTC, tkuchiki approved these changes
LGTM, thank you!

2024-04-12 13:49 UTC, merged